### ISSUE TITLE
Create company pages (list company job posts)

### ISSUE THREAD

**Issue by Sneruall** [Sneruall/greendeed#17]
**EDIT:**

**Part 1**

- [x] Make sure to also create a database with company data only (company id, name and description maybe?). 

- [x] Adjust the checking of company name existence to check in this db instead of in list of all jobs. And also make sure to pull all the data (not just the id), so you can easily display the company name next to the field instead of only id.
- [x] Refactoring

Reason for this is that we can than centrally keep the company data.

**Part 2**
Then we adjust the form:

- [x] Start with company data only. Based on entered company name, either hide the company description or show the description field (not adjustable anymore afterwards, needs to contact us via email (same for name and so forth).
- [x] Show the company name clickable next to the company name field if there is a match (so you can visit the company page from here, new tab opens).

**Part 3**
--------

- [x] create a new [...slug] based page that renders a list of jobs for a given company based on the id in the url E.g. /metaverse-companies/ez360-fha4j3j

- [x] make sure to assign an id to a company in the database (and check if the company already exists to assign the existing id to a new job listing). See issue related to live feedback form values.

- [x] list all jobs that have the same id as given in the url.
-
- [x] also check if the company name from url is correct (matching the id from db), if not do a redirect (like done for job pages)
- [x] Refactoring
Example page: https://remotive.com/remote-companies/tanooki-labs-15864
